"""studentRecords

Revision ID: bdcd2204b45c
Revises: 
Create Date: 2025-08-04 00:32:52.092165

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bdcd2204b45c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('studentRecords',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('course', sa.Integer(), nullable=False),
    sa.Column('performance', sa.Boolean(), nullable=False),
    sa.Column('duties', sa.Integer(), nullable=False),
    sa.Column('transition', sa.Integer(), nullable=False),
    sa.Column('general_cleaning', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_index(op.f('ix_studentRecords_id'), 'studentRecords', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_studentRecords_id'), table_name='studentRecords')
    op.drop_table('studentRecords')
    # ### end Alembic commands ###
